// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotPaxMsg.proto

package com.hotpaxos.pb;

public final class HotPaxMsg {
    private HotPaxMsg() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface SynOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.hotpaxos.pb.Syn)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string message = 1;</code>
         */
        String getMessage();
        /**
         * <code>string message = 1;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();
    }
    /**
     * Protobuf type {@code com.hotpaxos.pb.Syn}
     */
    public  static final class Syn extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.hotpaxos.pb.Syn)
            SynOrBuilder {
        // Use Syn.newBuilder() to construct.
        private Syn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Syn() {
            message_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Syn(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_Syn_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_Syn_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Syn.class, Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;
        private volatile Object message_;
        /**
         * <code>string message = 1;</code>
         */
        public String getMessage() {
            Object ref = message_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }
        /**
         * <code>string message = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Syn)) {
                return super.equals(obj);
            }
            Syn other = (Syn) obj;

            boolean result = true;
            result = result && getMessage()
                    .equals(other.getMessage());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Syn parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Syn parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Syn parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Syn parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Syn parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Syn parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Syn parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Syn parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Syn parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Syn parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Syn parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Syn parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Syn prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.hotpaxos.pb.Syn}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.hotpaxos.pb.Syn)
                SynOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Syn_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Syn_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Syn.class, Builder.class);
            }

            // Construct using com.hotpaxos.pb.HotPaxMsg.Syn.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                message_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Syn_descriptor;
            }

            public Syn getDefaultInstanceForType() {
                return Syn.getDefaultInstance();
            }

            public Syn build() {
                Syn result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Syn buildPartial() {
                Syn result = new Syn(this);
                result.message_ = message_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Syn) {
                    return mergeFrom((Syn)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Syn other) {
                if (other == Syn.getDefaultInstance()) return this;
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Syn parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Syn) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object message_ = "";
            /**
             * <code>string message = 1;</code>
             */
            public String getMessage() {
                Object ref = message_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string message = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessage(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string message = 1;</code>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }
            /**
             * <code>string message = 1;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.hotpaxos.pb.Syn)
        }

        // @@protoc_insertion_point(class_scope:com.hotpaxos.pb.Syn)
        private static final Syn DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Syn();
        }

        public static Syn getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Syn>
                PARSER = new com.google.protobuf.AbstractParser<Syn>() {
            public Syn parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Syn(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Syn> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Syn> getParserForType() {
            return PARSER;
        }

        public Syn getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SynAckOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.hotpaxos.pb.SynAck)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 addId = 1;</code>
         */
        int getAddId();

        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */
        int getMetaDataCount();
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */
        boolean containsMetaData(
                String key);
        /**
         * Use {@link #getMetaDataMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getMetaData();
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */
        java.util.Map<String, String>
        getMetaDataMap();
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        String getMetaDataOrDefault(
                String key,
                String defaultValue);
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        String getMetaDataOrThrow(
                String key);

        /**
         * <code>repeated string scope = 3;</code>
         */
        java.util.List<String>
        getScopeList();
        /**
         * <code>repeated string scope = 3;</code>
         */
        int getScopeCount();
        /**
         * <code>repeated string scope = 3;</code>
         */
        String getScope(int index);
        /**
         * <code>repeated string scope = 3;</code>
         */
        com.google.protobuf.ByteString
        getScopeBytes(int index);

        /**
         * <code>int32 tid = 4;</code>
         */
        int getTid();
    }
    /**
     * Protobuf type {@code com.hotpaxos.pb.SynAck}
     */
    public  static final class SynAck extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.hotpaxos.pb.SynAck)
            SynAckOrBuilder {
        // Use SynAck.newBuilder() to construct.
        private SynAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private SynAck() {
            addId_ = 0;
            scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            tid_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private SynAck(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            addId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                metaData_ = com.google.protobuf.MapField.newMapField(
                                        MetaDataDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000002;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    metaData__ = input.readMessage(
                                    MetaDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            metaData_.getMutableMap().put(
                                    metaData__.getKey(), metaData__.getValue());
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                scope_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            scope_.add(s);
                            break;
                        }
                        case 32: {

                            tid_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    scope_ = scope_.getUnmodifiableView();
                }
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 2:
                    return internalGetMetaData();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SynAck.class, Builder.class);
        }

        private int bitField0_;
        public static final int ADDID_FIELD_NUMBER = 1;
        private int addId_;
        /**
         * <code>int32 addId = 1;</code>
         */
        public int getAddId() {
            return addId_;
        }

        public static final int METADATA_FIELD_NUMBER = 2;
        private static final class MetaDataDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }
        private com.google.protobuf.MapField<
                String, String> metaData_;
        private com.google.protobuf.MapField<String, String>
        internalGetMetaData() {
            if (metaData_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MetaDataDefaultEntryHolder.defaultEntry);
            }
            return metaData_;
        }

        public int getMetaDataCount() {
            return internalGetMetaData().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        public boolean containsMetaData(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            return internalGetMetaData().getMap().containsKey(key);
        }
        /**
         * Use {@link #getMetaDataMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getMetaData() {
            return getMetaDataMap();
        }
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        public java.util.Map<String, String> getMetaDataMap() {
            return internalGetMetaData().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        public String getMetaDataOrDefault(
                String key,
                String defaultValue) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, String> map =
                    internalGetMetaData().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; metaData = 2;</code>
         */

        public String getMetaDataOrThrow(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, String> map =
                    internalGetMetaData().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int SCOPE_FIELD_NUMBER = 3;
        private com.google.protobuf.LazyStringList scope_;
        /**
         * <code>repeated string scope = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getScopeList() {
            return scope_;
        }
        /**
         * <code>repeated string scope = 3;</code>
         */
        public int getScopeCount() {
            return scope_.size();
        }
        /**
         * <code>repeated string scope = 3;</code>
         */
        public String getScope(int index) {
            return scope_.get(index);
        }
        /**
         * <code>repeated string scope = 3;</code>
         */
        public com.google.protobuf.ByteString
        getScopeBytes(int index) {
            return scope_.getByteString(index);
        }

        public static final int TID_FIELD_NUMBER = 4;
        private int tid_;
        /**
         * <code>int32 tid = 4;</code>
         */
        public int getTid() {
            return tid_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (addId_ != 0) {
                output.writeInt32(1, addId_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetMetaData(),
                            MetaDataDefaultEntryHolder.defaultEntry,
                            2);
            for (int i = 0; i < scope_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, scope_.getRaw(i));
            }
            if (tid_ != 0) {
                output.writeInt32(4, tid_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (addId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, addId_);
            }
            for (java.util.Map.Entry<String, String> entry
                    : internalGetMetaData().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        metaData__ = MetaDataDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, metaData__);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < scope_.size(); i++) {
                    dataSize += computeStringSizeNoTag(scope_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getScopeList().size();
            }
            if (tid_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, tid_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof SynAck)) {
                return super.equals(obj);
            }
            SynAck other = (SynAck) obj;

            boolean result = true;
            result = result && (getAddId()
                    == other.getAddId());
            result = result && internalGetMetaData().equals(
                    other.internalGetMetaData());
            result = result && getScopeList()
                    .equals(other.getScopeList());
            result = result && (getTid()
                    == other.getTid());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ADDID_FIELD_NUMBER;
            hash = (53 * hash) + getAddId();
            if (!internalGetMetaData().getMap().isEmpty()) {
                hash = (37 * hash) + METADATA_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMetaData().hashCode();
            }
            if (getScopeCount() > 0) {
                hash = (37 * hash) + SCOPE_FIELD_NUMBER;
                hash = (53 * hash) + getScopeList().hashCode();
            }
            hash = (37 * hash) + TID_FIELD_NUMBER;
            hash = (53 * hash) + getTid();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static SynAck parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static SynAck parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static SynAck parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static SynAck parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static SynAck parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static SynAck parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static SynAck parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static SynAck parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static SynAck parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static SynAck parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static SynAck parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static SynAck parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(SynAck prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.hotpaxos.pb.SynAck}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.hotpaxos.pb.SynAck)
                SynAckOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMetaData();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMutableMetaData();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SynAck.class, Builder.class);
            }

            // Construct using com.hotpaxos.pb.HotPaxMsg.SynAck.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                addId_ = 0;

                internalGetMutableMetaData().clear();
                scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                tid_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_SynAck_descriptor;
            }

            public SynAck getDefaultInstanceForType() {
                return SynAck.getDefaultInstance();
            }

            public SynAck build() {
                SynAck result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SynAck buildPartial() {
                SynAck result = new SynAck(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.addId_ = addId_;
                result.metaData_ = internalGetMetaData();
                result.metaData_.makeImmutable();
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    scope_ = scope_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.scope_ = scope_;
                result.tid_ = tid_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SynAck) {
                    return mergeFrom((SynAck)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SynAck other) {
                if (other == SynAck.getDefaultInstance()) return this;
                if (other.getAddId() != 0) {
                    setAddId(other.getAddId());
                }
                internalGetMutableMetaData().mergeFrom(
                        other.internalGetMetaData());
                if (!other.scope_.isEmpty()) {
                    if (scope_.isEmpty()) {
                        scope_ = other.scope_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureScopeIsMutable();
                        scope_.addAll(other.scope_);
                    }
                    onChanged();
                }
                if (other.getTid() != 0) {
                    setTid(other.getTid());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SynAck parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SynAck) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int addId_ ;
            /**
             * <code>int32 addId = 1;</code>
             */
            public int getAddId() {
                return addId_;
            }
            /**
             * <code>int32 addId = 1;</code>
             */
            public Builder setAddId(int value) {

                addId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 addId = 1;</code>
             */
            public Builder clearAddId() {

                addId_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, String> metaData_;
            private com.google.protobuf.MapField<String, String>
            internalGetMetaData() {
                if (metaData_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MetaDataDefaultEntryHolder.defaultEntry);
                }
                return metaData_;
            }
            private com.google.protobuf.MapField<String, String>
            internalGetMutableMetaData() {
                onChanged();;
                if (metaData_ == null) {
                    metaData_ = com.google.protobuf.MapField.newMapField(
                            MetaDataDefaultEntryHolder.defaultEntry);
                }
                if (!metaData_.isMutable()) {
                    metaData_ = metaData_.copy();
                }
                return metaData_;
            }

            public int getMetaDataCount() {
                return internalGetMetaData().getMap().size();
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public boolean containsMetaData(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                return internalGetMetaData().getMap().containsKey(key);
            }
            /**
             * Use {@link #getMetaDataMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, String> getMetaData() {
                return getMetaDataMap();
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public java.util.Map<String, String> getMetaDataMap() {
                return internalGetMetaData().getMap();
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public String getMetaDataOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, String> map =
                        internalGetMetaData().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public String getMetaDataOrThrow(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, String> map =
                        internalGetMetaData().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMetaData() {
                internalGetMutableMetaData().getMutableMap()
                        .clear();
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public Builder removeMetaData(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                internalGetMutableMetaData().getMutableMap()
                        .remove(key);
                return this;
            }
            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableMetaData() {
                return internalGetMutableMetaData().getMutableMap();
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */
            public Builder putMetaData(
                    String key,
                    String value) {
                if (key == null) { throw new NullPointerException(); }
                if (value == null) { throw new NullPointerException(); }
                internalGetMutableMetaData().getMutableMap()
                        .put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; metaData = 2;</code>
             */

            public Builder putAllMetaData(
                    java.util.Map<String, String> values) {
                internalGetMutableMetaData().getMutableMap()
                        .putAll(values);
                return this;
            }

            private com.google.protobuf.LazyStringList scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureScopeIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    scope_ = new com.google.protobuf.LazyStringArrayList(scope_);
                    bitField0_ |= 0x00000004;
                }
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getScopeList() {
                return scope_.getUnmodifiableView();
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public int getScopeCount() {
                return scope_.size();
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public String getScope(int index) {
                return scope_.get(index);
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public com.google.protobuf.ByteString
            getScopeBytes(int index) {
                return scope_.getByteString(index);
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public Builder setScope(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureScopeIsMutable();
                scope_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public Builder addScope(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureScopeIsMutable();
                scope_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public Builder addAllScope(
                    Iterable<String> values) {
                ensureScopeIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, scope_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public Builder clearScope() {
                scope_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string scope = 3;</code>
             */
            public Builder addScopeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureScopeIsMutable();
                scope_.add(value);
                onChanged();
                return this;
            }

            private int tid_ ;
            /**
             * <code>int32 tid = 4;</code>
             */
            public int getTid() {
                return tid_;
            }
            /**
             * <code>int32 tid = 4;</code>
             */
            public Builder setTid(int value) {

                tid_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 tid = 4;</code>
             */
            public Builder clearTid() {

                tid_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.hotpaxos.pb.SynAck)
        }

        // @@protoc_insertion_point(class_scope:com.hotpaxos.pb.SynAck)
        private static final SynAck DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new SynAck();
        }

        public static SynAck getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SynAck>
                PARSER = new com.google.protobuf.AbstractParser<SynAck>() {
            public SynAck parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SynAck(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SynAck> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<SynAck> getParserForType() {
            return PARSER;
        }

        public SynAck getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface AckOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.hotpaxos.pb.Ack)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 appid = 1;</code>
         */
        int getAppid();
    }
    /**
     * Protobuf type {@code com.hotpaxos.pb.Ack}
     */
    public  static final class Ack extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.hotpaxos.pb.Ack)
            AckOrBuilder {
        // Use Ack.newBuilder() to construct.
        private Ack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Ack() {
            appid_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Ack(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            appid_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_Ack_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return HotPaxMsg.internal_static_com_hotpaxos_pb_Ack_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Ack.class, Builder.class);
        }

        public static final int APPID_FIELD_NUMBER = 1;
        private int appid_;
        /**
         * <code>int32 appid = 1;</code>
         */
        public int getAppid() {
            return appid_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (appid_ != 0) {
                output.writeInt32(1, appid_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (appid_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, appid_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Ack)) {
                return super.equals(obj);
            }
            Ack other = (Ack) obj;

            boolean result = true;
            result = result && (getAppid()
                    == other.getAppid());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + APPID_FIELD_NUMBER;
            hash = (53 * hash) + getAppid();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Ack parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Ack parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Ack parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Ack parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Ack parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Ack parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Ack parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Ack parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Ack parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Ack parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Ack parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Ack parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Ack prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.hotpaxos.pb.Ack}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.hotpaxos.pb.Ack)
                AckOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Ack_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Ack_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Ack.class, Builder.class);
            }

            // Construct using com.hotpaxos.pb.HotPaxMsg.Ack.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                appid_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HotPaxMsg.internal_static_com_hotpaxos_pb_Ack_descriptor;
            }

            public Ack getDefaultInstanceForType() {
                return Ack.getDefaultInstance();
            }

            public Ack build() {
                Ack result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Ack buildPartial() {
                Ack result = new Ack(this);
                result.appid_ = appid_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Ack) {
                    return mergeFrom((Ack)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Ack other) {
                if (other == Ack.getDefaultInstance()) return this;
                if (other.getAppid() != 0) {
                    setAppid(other.getAppid());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Ack parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Ack) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int appid_ ;
            /**
             * <code>int32 appid = 1;</code>
             */
            public int getAppid() {
                return appid_;
            }
            /**
             * <code>int32 appid = 1;</code>
             */
            public Builder setAppid(int value) {

                appid_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 appid = 1;</code>
             */
            public Builder clearAppid() {

                appid_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.hotpaxos.pb.Ack)
        }

        // @@protoc_insertion_point(class_scope:com.hotpaxos.pb.Ack)
        private static final Ack DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Ack();
        }

        public static Ack getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Ack>
                PARSER = new com.google.protobuf.AbstractParser<Ack>() {
            public Ack parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Ack(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Ack> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Ack> getParserForType() {
            return PARSER;
        }

        public Ack getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_hotpaxos_pb_Syn_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_hotpaxos_pb_Syn_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_hotpaxos_pb_SynAck_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_hotpaxos_pb_SynAck_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_hotpaxos_pb_Ack_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_hotpaxos_pb_Ack_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\017HotPaxMsg.proto\022\017com.hotpaxos.pb\"\026\n\003Sy" +
                        "n\022\017\n\007message\030\001 \001(\t\"\235\001\n\006SynAck\022\r\n\005addId\030\001" +
                        " \001(\005\0227\n\010metaData\030\002 \003(\0132%.com.hotpaxos.pb" +
                        ".SynAck.MetaDataEntry\022\r\n\005scope\030\003 \003(\t\022\013\n\003" +
                        "tid\030\004 \001(\005\032/\n\rMetaDataEntry\022\013\n\003key\030\001 \001(\t\022" +
                        "\r\n\005value\030\002 \001(\t:\0028\001\"\024\n\003Ack\022\r\n\005appid\030\001 \001(\005" +
                        "B\013B\tHotPaxMsgb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_com_hotpaxos_pb_Syn_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_hotpaxos_pb_Syn_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_hotpaxos_pb_Syn_descriptor,
                new String[] { "Message", });
        internal_static_com_hotpaxos_pb_SynAck_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_hotpaxos_pb_SynAck_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_hotpaxos_pb_SynAck_descriptor,
                new String[] { "AddId", "MetaData", "Scope", "Tid", });
        internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_descriptor =
                internal_static_com_hotpaxos_pb_SynAck_descriptor.getNestedTypes().get(0);
        internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_hotpaxos_pb_SynAck_MetaDataEntry_descriptor,
                new String[] { "Key", "Value", });
        internal_static_com_hotpaxos_pb_Ack_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_com_hotpaxos_pb_Ack_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_hotpaxos_pb_Ack_descriptor,
                new String[] { "Appid", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
